# Generated by Django 4.1.2 on 2022-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("slackUsername", models.CharField(max_length=200)),
                ("backend", models.BooleanField()),
                ("age", models.IntegerField()),
                ("bio", models.TextField()),
            ],
        ),
    ]
